### ISSUE TITLE
Create worksheet / checklist for pull request readiness

### ISSUE THREAD

**Issue by jennybc** [r-lib/usethis#1176]
Typical venue for usage: right before a tidyverse dev day

**Comment by jennybc** [comment]
I'm going to draft this here and call it "done, enough, for now". Turning it into a concrete checklist will have to happen right before an actual event, with current versions/expectations.

---

- [ ] Update R, RStudio (<https://happygitwithr.com/install-r-rstudio.html>)
- [ ] Create a GitHub.com account (<https://happygitwithr.com/github-acct.html>)
- [ ] Install Git (<https://happygitwithr.com/install-git.html>)
- [ ] Configure local Git `user.name` and `user.email` (<https://happygitwithr.com/hello-git.html>)
- [ ] `usethis::git_vaccinate()` (<https://usethis.r-lib.org/reference/git_vaccinate.html>)
- [ ] `usethis::create_github_token()` + `gitcreds::gitcreds_set()` (<https://usethis.r-lib.org/articles/articles/git-credentials.html>)
- [ ] `usethis::git_sitrep()`
- [ ] Successfully complete a low-stakes PR, along the lines of [proposing a new adjective to praise](https://usethis.r-lib.org/articles/articles/pr-functions.html), e.g. to submit food preferences for the dev day. Use `create_from_github()` and the `pr_functions()`, just like the linked article.
